### ISSUE TITLE
Support for hasOwnProperty

### ISSUE THREAD

**Issue by warappa** [koculu/Topaz#18]
**Describe the bug**
It seems that `hasOwnProperty` is not supported by Topaz.

Is there an option or something to support `hasOwnProperty`?

**To Reproduce**
```csharp
var engine = new TopazEngine();
engine.ExecuteScript("""let ob =  { "a": {"b": "123" }};""");
var result = engine.ExecuteExpression("ob['a'].hasOwnProperty('b')");
Console.WriteLine(result);
```

**Expected behavior**
Test code should print "true". Instead, it crashes.

```
Tenray.Topaz.TopazException: 'Function ob.a.hasOwnProperty is not defined.'
   at Tenray.Topaz.ErrorHandling.Exceptions.ThrowFunctionIsNotDefined(Object callee, ScriptExecutor scope)
   at Tenray.Topaz.Core.ScriptExecutor.CallFunction(Object callee, IReadOnlyList`1 args, Boolean optional, CancellationToken token)
   at Tenray.Topaz.Expressions.CallExpressionHandler.Execute(ScriptExecutor scriptExecutor, Node expression, CancellationToken token)
   at Tenray.Topaz.Core.ScriptExecutor.ExecuteStatement(Node statement, CancellationToken token)
   at Tenray.Topaz.Core.ScriptExecutor.ExecuteExpressionAndGetValue(Expression expression, CancellationToken token)
   at Tenray.Topaz.Core.ScriptExecutor.Tenray.Topaz.ITopazEngineScope.ExecuteExpression(String code, CancellationToken token)
   at Tenray.Topaz.TopazEngine.ExecuteExpression(String code, CancellationToken token)
   at Program.<Main>$(String[] args) in C:\Users\rtda\source\repos\ConsoleApp7\ConsoleApp7\Program.cs:line 26
```

**Desktop:**
 - Operating System: Windows
 - Topaz Version: 1.3.6

**Comment by koculu** [comment]
Could you please test if  `Contains` method works for you?

**Comment by warappa** [comment]
Thanks for the fast response!

I tried `Contains(...)` and it worked.

In a broader sense, I actually wanted to ask why standard JavaScript methods like good old `hasOwnProperty(...)` are not supported? Is this by design?

**Comment by koculu** [comment]
> Thanks for the fast response!
> 
> I tried `Contains(...)` and it worked.
> 
> In a broader sense, I actually wanted to ask why standard JavaScript methods like good old `hasOwnProperty(...)` are not supported? Is this by design?

Simply, I haven't needed it until you asked :). And thanks for asking.
I have implemented alternative options with the following pull request:
https://github.com/koculu/Topaz/pull/19

**Comment by warappa** [comment]
Thanks for looking into it and fixing it so quickly! 👍
